name: HungryHeaven CI

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Validate Docker Compose
        run: docker compose config

      - name: Build Docker Images
        run: docker compose build